[package]
name = "aoc-{{ year }}-{{ day_two_digits }}"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc_framework = { path = "../../libs/aoc_framework" }
